function [CC2] = getCCLs(mask)
% Compute bounding boxes using Connected Component Labeling
CCL  = bwconncomp ( mask );
CC   = regionprops( CCL,'basic' );
CC2 = [];
for i=1:length(CC)
    CC2 = [CC2; struct('x',CC(i).BoundingBox(1),...
        'y',CC(i).BoundingBox(2),...
        'w',CC(i).BoundingBox(3),...
        'h',CC(i).BoundingBox(4),...
        'size',CC(i).BoundingBox(3)*CC(i).BoundingBox(4),...
        'fr',CC(i).Area / (CC(i).BoundingBox(3)*CC(i).BoundingBox(4)),...
        'ff',(CC(i).BoundingBox(3)/CC(i).BoundingBox(4))...
        )];
end
end

